# Quigely staging values for cver-api.

replicaCount: 1

nameOverride: "stage"

app:
  dbName: "cver_stage"
  dbHost: "cver-mysql.cver.svc.cluster.local"
  dbUser: "cver"
  runMigrations: true
  envName: "stage"

test:
  test: true

image:
  repository: politeauthority/cver-api
  pullPolicy: Always
  tag: "0.0.1"
