# Quigely staging values for cver-api.

replicaCount: 1

nameOverride: "prod"

app:
  dbName: "cver_prod"
  dbHost: "cver-mysql.cver.svc.cluster.local"
  dbUser: "cver"
  runMigrations: true

image:
  repository: politeauthority/cver-api
  pullPolicy: IfNotPresent
  tag: "0.0.1b"

mysql:
  enabled: true
  nameOverride: cver-mysql
  fullnameOverride: cver-mysql
  primary:
    persistence:
      storageClass: nfs-client
