# Quigely staging values for cver-api.

replicaCount: 1

nameOverride: "prod"

app:
  runMigrations: true
  envName: "prod"
  logHealthChecks: false
  database:
    name: "cver_prod"
    host: "cver-mysql.cver.svc.cluster.local"
    user: "cver"

image:
  repository: harbor.squid-ink.us/cver/cver-api
  pullPolicy: IfNotPresent
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor

ingress:
  enabled: true
  className: nginx-public
  hosts:
    - host: cver.alix.lol
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - cver.alix.lol
    secretName: cver-prod-tls

mysql:
  enabled: false
  nameOverride: cver-mysql
  fullnameOverride: cver-mysql
  primary:
    persistence:
      storageClass: nfs-client
