# Quigely staging values for cver-api.

replicaCount: 1

nameOverride: "ephem"

app:
  dbHost: "cver-mysql.cver.svc.cluster.local"
  dbUser: "cver"
  runMigrations: true
  envName: "ephem"

test:
  test: true

image:
  repository: harbor.squid-ink.us/politeauthority/cver-api
  pullPolicy: Always
  tag: "ephem"

imagePullSecrets:
  - name: harbor

ingress:
  enabled: true
  className: nginx-private
  hosts:
    - host: stage.cver.colfax.int
      paths:
        - path: /
          pathType: Prefix
