# Quigely dev values for cver-api.

replicaCount: 1

nameOverride: "dev"

app:
  dbName: "cver_dev"
  dbHost: "cver-mysql.cver.svc.cluster.local"
  dbUser: "cver"
  runMigrations: true
  envName: "dev"
  debug: true

test:
  test: true

image:
  repository: harbor.squid-ink.us/politeauthority/cver-api
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor

ingress:
  enabled: true
  className: nginx-private
  hosts:
    - host: dev.cver.colfax.int
      paths:
        - path: /
          pathType: Prefix
