# Quigely staging values for cver-api.

replicaCount: 1

nameOverride: "stage"

app:
  logLevel: "DEBUG"
  dbName: "cver_stage"
  dbHost: "cver-mysql.cver.svc.cluster.local"
  dbUser: "cver"
  runMigrations: true
  envName: "stage"
  logHealthChecks: false

test:
  test: true

image:
  repository: harbor.squid-ink.us/politeauthority/cver-api
  pullPolicy: Always
  tag: "stage-latest"

imagePullSecrets:
  - name: harbor

ingress:
  enabled: true
  className: nginx-private
  hosts:
    - host: stage.cver.colfax.int
      paths:
        - path: /
          pathType: Prefix
