# Quigely test values for cver-api.

replicaCount: 1

nameOverride: "test"

app:
  logLevel: "DEBUG"
  runMigrations: true
  envName: "test"
  database:
    name: "cver_test"
    host: "cver-mysql.cver.svc.cluster.local"
    user: "cver"


test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-api
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor-registry
