# Quigely staging values for cver-api.

replicaCount: 1

nameOverride: "prod"

app:
  dbName: "cver_prod"
  dbHost: "cver-mysql.cver.svc.cluster.local"
  dbUser: "cver"
  runMigrations: true

image:
  repository: harbor.squid-ink.us/politeauthority/cver-api
  pullPolicy: IfNotPresent
  tag: "0.0.1"

imagePullSecrets:
  - name: harbor

ingress:
  enabled: true
  className: nginx-public
  hosts:
    - host: cver.squid-ink.us
      paths:
        - path: /
          pathType: Prefix
  tls:
  - hosts:
    - cver.squid-ink.us
    secretName: cver-prod-tls

mysql:
  enabled: true
  nameOverride: cver-mysql
  fullnameOverride: cver-mysql
  primary:
    persistence:
      storageClass: nfs-client
