# Quigely staging values for cver-api.

replicaCount: 1

nameOverride: "stage"

app:
  logLevel: "DEBUG"
  runMigrations: true
  envName: "stage"
  logHealthChecks: false
  jwtExpireMinutes: 1440
  database:
    name: "cver_stage"
    host: "cver-mysql.cver.svc.cluster.local"
    user: "cver"

test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-api
  pullPolicy: Always
  tag: "stage-latest"

imagePullSecrets:
  - name: harbor-registry

ingress:
  enabled: true
  className: nginx-private
  hosts:
    - host: stage.cver.colfax.int
      paths:
        - path: /
          pathType: Prefix
