version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/src/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/tests/"
    schedule:
      interval: "weekly"

