version: '3'

vars:
  CVER_DIR: "."

tasks:
  build:
    cmds:
      - cp -r {{.CVER_DIR}}/src {{.CVER_DIR}}/docker/api/
      - cp -r {{.CVER_DIR}}/tests {{.CVER_DIR}}/docker/api/
      - rm -rf {{.CVER_DIR}}/docker/api/src/build
      - rm -rf {{.CVER_DIR}}/docker/api/src/dist
      - rm -rf {{.CVER_DIR}}/docker/api/src/cver.egg-info
      - docker build -t politeauthority/cver-api:{{.CVER_API_TAG}} {{.CVER_DIR}}/docker/api
      - rm -rf {{.CVER_DIR}}/docker/api/src
      - rm -rf {{.CVER_DIR}}/docker/api/tests
      - echo "Completed build politeauthority/cver-api:{{.CVER_API_TAG}}"
    silent: false
  dev-run:
    cmds:
      - docker run --name="cver" -d -v {{.CVER_DIR}}/src:/app -v {{.CVER_DIR}}/tests:/tests -p 5001:5001 -e CVER_DB_PASS="${CVER_DB_PASS}" politeauthority/cver:{{.CVER_TAG}} tail -f /dev/null
      - docker network connect cver cver
      - echo "Success"
    silent: false
  dev-exec:
    cmds:
      - docker exec -it cver bash
  dev-stop:
    cmds:
      - docker rm -f cver
  pre-commit-lint:
    cmds: 
      - cd ./src && flake8 cver --config=flake8 --count --show-source --statistics
  k8s-exec-stage:
    cmds:
      - |
        POD=$(kubectl get pods -l app.kubernetes.io/name=cver-api --no-headers | cut -d' ' -f1)
        echo "Logging into $POD"
        kubectl exec -it ${POD} -- bash
    silent: true