#!/bin/sh -l
# Cver Test - Unit
set -e
echo "Cver Test Suite Starting"
WORKING_DIR="/current"
TEST_DIR="/tests"

# mkdir /workdir
# cd /workdir
# git clone https://github.com/politeauthority/cver.git
# cd  cver

# git fetch origin
# git checkout origin/cver-test

/bin/cver-build

cd ${TEST_DIR}/unit
pytest --md report.md --vcr-record=none
