#!/bin/sh -l
# Cver Test - Unit
# Runs unit tests
# Operations
#  - Build Cver
#  - Builds Cver Test Tools
set -e
echo "Cver Test Suite Starting"
NO_BUILD=${1}

WORKING_DIR="/current"
TEST_DIR="/current/tests"

if [ "$NO_BUILD" = "no-build" ]; then
    echo "Not building Cver"
else
    /bin/cver-build
fi

cd ${TEST_DIR}
echo "Building Cver Test Tools"
pip install .

cd ${TEST_DIR}/unit
pytest -vvv
