#!/bin/sh -l
# Cver Build

set -e
echo "Running Cver Build"

SOURCE_DIR="/current/src"
TEST_DIR="/current/tests"
echo "Using work dir: ${SOURCE_DIR}"

# Remove old Cver instances
rm -rf /usr/local/lib/python3.10/site-packages/cver-*.dist-info
rm -rf ${SOURCE_DIR}/build
rm -rf ${SOURCE_DIR}/cver.egg-info

# Installing Cver
cd $SOURCE_DIR
pip install .
echo "Cver Build Success!"