#!/bin/sh -l
# Cver Build

set -e
echo "Running Cver Build"

WORKING_DIR="/current"
TEST_DIR="/tests"
echo "Using work dir: ${WORKING_DIR}"

# Remove old Cver instances
rm -rf /usr/local/lib/python3.10/site-packages/cver-*.dist-info
rm -rf ${WORKING_DIR}/build
rm -rf ${WORKING_DIR}/cver.egg-info

# Installing Cver
cd $WORKING_DIR
pip install .

cd $TEST_DIR
pip install .

# Flake8 Source
flake8 ${WORKING_DIR}/cver --config=${WORKING_DIR}/flake8 --count --show-source --statistics

# Flake8 Tests
flake8 /tests --config=/tests/flake8 --count --show-source --statistics

# # Run Unit Tests
# pytest ${TEST_DIR}/unit

# # Run Regression Tests
# pytest ${TEST_DIR}/regression
