#!/bin/sh -l
# Cver Build

set -e
echo "Running Cver Build"

rm -rf /usr/local/lib/python3.10/site-packages/cver*
rm -rf /app/build
rm -rf /app/cver.egg-info

cd /app
python3 setup.py build
python3 setup.py install
