#!/bin/sh -l
# Cver Build

set -e
echo "Running Cver Build"

rm -rf /usr/local/lib/python3.10/site-packages/cver*
rm -rf /app/build
rm -rf /app/cver.egg-info

cd /app
python3 setup.py build
python3 setup.py install
# Flake8 Source
flake8 /app/cver --config=/app/flake8 --count --show-source --statistics

# Flake8 Tests
flake8 /tests --config=/tests/flake8 --count --show-source --statistics

cd /tests/unit
pytest
