#!/bin/sh -l
# Cver Build Test Suite

set -e
echo "Running Cver Build Test Suite"

rm -rf /usr/local/lib/python3.10/site-packages/cver*
rm -rf /tests/build
rm -rf /tests/cver_test_tools.egg-info

cd /tests
python3 setup.py build
python3 setup.py install

# Flake8 Source
flake8 /app/cver --config=/app/flake8 --count --show-source --statistics

# Flake8 Tests
flake8 /tests --config=/tests/flake8 --count --show-source --statistics

# echo "Running tests"
cd /tests/unit
pytest
