#!/bin/sh -l
# Cver Build

set -e
echo "Running Cver Build"

# echo "Removing Pignus"
# rm -rf /usr/local/lib/python3.9/site-packages/pignus-0.0.*
# rm -rf /app/build
# rm -rf /app/dist
# rm -rf /app/pignus.egg-info

rm -rf /usr/local/lib/python3.10/site-packages/cver*
rm -rf /app/build
rm -rf /app/cver.egg-info

cd /app
pip install .

# Flake8 Source
flake8 /app/cver --config=/app/flake8 --count --show-source --statistics

# Flake8 Tests
flake8 /tests --config=/tests/flake8 --count --show-source --statistics

# echo "Running tests"
cd /tests/unit
pytest
