# Cver Test
# Quigely Stage values

nameOverride: "stage"

app:
  api_url: "http://cver-api-dev"
  logLevel: "DEBUG"
  envName: "stage"
  debug: true
  database:
    name: "cver_stage"
    host: "cver-mysql.cver.svc.cluster.local"
    user: "cver"

image:
  repository: harbor.squid-ink.us/cver/cver-test
  pullPolicy: Always
  tag: "stage-latest"

imagePullSecrets:
  - name: harbor
