# Cver Test
# Quigely Test values

replicaCount: 1

nameOverride: "test"

app:
  logLevel: "DEBUG"
  cverCicd: "true"
  envName: "test"
  debug: true
  database:
    name: "cver_dev"
    host: "cver-mysql.cver.svc.cluster.local"
    user: "cver"

image:
  repository: harbor.squid-ink.us/cver/cver-test
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor
