# Quigely dev values for cver-test.

replicaCount: 1

nameOverride: "dev"

app:
  logLevel: "DEBUG"
  envName: "test"
  debug: true

image:
  repository: harbor.squid-ink.us/cver/cver-test
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor
