# Cver Test
# Quigely Dev values

nameOverride: "dev"

app:
  api_url: "http://cver-api-dev"
  logLevel: "DEBUG"
  envName: "dev"
  debug: true
  database:
    name: "cver_dev"
    host: "cver-mysql.cver.svc.cluster.local"
    user: "cver"

image:
  repository: harbor.squid-ink.us/cver/cver-test
  pullPolicy: Always

imagePullSecrets:
  - name: harbor
