# Default values for cver-test.

replicaCount: 1

app:
  apiUrl: "http://cver-api"
  branch: "main"
  logLevel: "DEBUG"
  envName: "prod"
  debug: false
  deployedAt: Unknown
  testDir: "/cicd/cver/tests/"
  cverTestCredsSecret: "cver-test-creds"
  database:
    name: "cver"
    host: "mysql"
    port: 3306
    user: "mysql-user"
    passwordSecretName: mysql-password
    passwordSecretKey: cver-api

image:
  repository: politeauthority/cver-test
  pullPolicy: IfNotPresent
  tag: "0.0.5"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  enabled: false
  nameOverride: cver-mysql
  primary:
    persistence:
      storageClass: nfs-client
