# Default values for cver-test.

replicaCount: 1

app:
  api_url: "http://cver-api"
  cverCicd: "false"
  logLevel: "DEBUG"
  envName: "prod"
  debug: false
  deployedAt: Unknown

image:
  repository: politeauthority/cver-test
  pullPolicy: IfNotPresent
  tag: "latest"


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  enabled: false
  nameOverride: cver-mysql
  primary:
    persistence:
      storageClass: nfs-client
