# Quigely stage values for cver-ingest

replicaCount: 1

nameOverride: "prod"

app:
  envName: "prod"
  debug: true
  apiUrl: "http://cver-api-prod"
  cron:
    schedule:  "40 * * * *"
    suspend: false

test:
  test: false

image:
  repository: harbor.squid-ink.us/cver/cver-ingest
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor
