# Quigely dev values for cver-ingest

nameOverride: "dev"

app:
  envName: "dev"
  apiUrl: "http://cver-api-dev"
  debug: true
  cron:
    suspend: true
    schedule:  "10,45 * * * *"

test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-ingest
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor
