apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cver-api.fullname" . }}
  labels:
    {{- include "cver-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cver-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        cver.deployed: "{{ .Values.app.deployedAt }}"
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cver-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # serviceAccountName: {{ include "cver-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.app.runMigrations }}
      initContainers:
      - name: cver-migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["python3", "/app/cver/migrate/migrate.py"]
        env:
          - name: CVER_ENV
            value: "{{ .Values.app.envName }}"
          - name: CVER_DB_HOST
            value: "{{ .Values.app.database.host }}"
          - name: CVER_DB_PORT
            value: "{{ .Values.app.database.port }}"
          - name: CVER_DB_NAME
            value: "{{ .Values.app.database.name }}"
          - name: CVER_DB_USER
            value: "{{ .Values.app.database.user }}"
          - name: CVER_DB_PASS
            valueFrom:
              secretKeyRef:
                key: {{ .Values.app.database.passwordSecretName }}
                name: {{ .Values.app.database.passwordSecretKey }}
          - name: CVER_DEPLOYED_AT
            value: "{{ .Values.app.deployedAt }}"
          {{- if .Values.test.test }}
          - name: CVER_TEST
            value: "true"
          - name: CVER_API_KEY
            valueFrom:
              secretKeyRef:
                key: admin-api-key
                name: cver-test-creds
          - name: CVER_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: admin-client-id
                name: cver-test-creds
          - name: CVER_TEST_ADMIN_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: admin-client-id
                name: cver-test-creds
          - name: CVER_TEST_ADMIN_API_KEY
            valueFrom:
              secretKeyRef:
                key: admin-api-key
                name: cver-test-creds
          - name: CVER_TEST_INGEST_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: ingest-client-id
                name: cver-test-creds
          - name: CVER_TEST_INGEST_API_KEY
            valueFrom:
              secretKeyRef:
                key: ingest-api-key
                name: cver-test-creds
          - name: CVER_TEST_ENGINE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: engine-client-id
                name: cver-test-creds
          - name: CVER_TEST_ENGINE_API_KEY
            valueFrom:
              secretKeyRef:
                key: engine-api-key
                name: cver-test-creds
          - name: CVER_TEST_EXPIRED_CLIENT_ID
            valueFrom:
              secretKeyRef:
                key: expired-client-id
                name: cver-test-creds
          - name: CVER_TEST_EXPIRED_API_KEY
            valueFrom:
              secretKeyRef:
                key: expired-api-key
                name: cver-test-creds
          - name: CVER_TEST_OPT_REGISTRY_URL
            valueFrom:
              secretKeyRef:
                key: option-registry-url
                name: cver-test-creds
          - name: CVER_TEST_OPT_REGISTRY_USER
            valueFrom:
              secretKeyRef:
                key: option-registry-user
                name: cver-test-creds
          - name: CVER_TEST_OPT_REGISTRY_PASS
            valueFrom:
              secretKeyRef:
                key:  option-registry-pass
                name: cver-test-creds
          - name: CVER_TEST_OPT_REGISTRY_REPO_GEN
            valueFrom:
              secretKeyRef:
                key:  option-registry-repo-general
                name: cver-test-creds
          {{- end }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if not .Values.app.runApiOnStart }}
          command: ["tail", "-f", "/dev/null"]
          {{- end }}
          env:
            - name: CVER_ENV
              value: "{{ .Values.app.envName }}"
            - name: CVER_LOG_LEVEL
              value: "{{ .Values.app.logLevel }}"
            - name: CVER_DB_HOST
              value: "{{ .Values.app.database.host }}"
            - name: CVER_DB_PORT
              value: "{{ .Values.app.database.port }}"
            - name: CVER_DB_NAME
              value: "{{ .Values.app.database.name }}"
            - name: CVER_DB_USER
              value: "{{ .Values.app.database.user }}"
            - name: CVER_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.app.database.passwordSecretName }}
                  name: {{ .Values.app.database.passwordSecretKey }}
            - name: CVER_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  key: cver-secret-key
                  name: cver-api
            - name: CVER_JWT_EXPIRE_MINUTES
              value: "{{ .Values.app.jwtExpireMinutes }}"
            - name: CVER_LOG_HEALTH_CHECKS
              value: "{{ .Values.app.logHealthChecks }}"
            {{- if .Values.test.test }}
            - name: CVER_TEST
              value: "true"
            # All of these should be removed eventually, since they're only needed in migrations.
            - name: CVER_TEST_ADMIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: admin-client-id
                  name: cver-test-creds
            - name: CVER_TEST_ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  key: admin-api-key
                  name: cver-test-creds
            - name: CVER_TEST_INGEST_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: ingest-client-id
                  name: cver-test-creds
            - name: CVER_TEST_INGEST_API_KEY
              valueFrom:
                secretKeyRef:
                  key: ingest-api-key
                  name: cver-test-creds
            - name: CVER_TEST_ENGINE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: engine-client-id
                  name: cver-test-creds
            - name: CVER_TEST_ENGINE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: engine-api-key
                  name: cver-test-creds
            - name: CVER_TEST_OPT_REGISTRY_URL
              valueFrom:
                secretKeyRef:
                  key: option-registry-url
                  name: cver-test-creds
            - name: CVER_TEST_OPT_REGISTRY_USER
              valueFrom:
                secretKeyRef:
                  key: option-registry-user
                  name: cver-test-creds
            - name: CVER_TEST_OPT_REGISTRY_PASS
              valueFrom:
                secretKeyRef:
                  key:  option-registry-pass
                  name: cver-test-creds
            - name: CVER_TEST_OPT_REGISTRY_REPO_GEN
              valueFrom:
                secretKeyRef:
                  key:  option-registry-repo-general
                  name: cver-test-creds
            {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          {{- if not .Values.app.debug }}
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 60
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 240
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
