apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cver-api.fullname" . }}
  labels:
    {{- include "cver-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cver-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cver-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      # serviceAccountName: {{ include "cver-api.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.app.runMigrations }}
      initContainers:
      - name: cver-migrations
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["python3", "/app/cver/migrate/migrate.py"]
        env:
          - name: CVER_DB_HOST
            value: "{{ .Values.app.dbHost }}"
          - name: CVER_DB_PORT
            value: "{{ .Values.app.dbPort }}"
          - name: CVER_DB_NAME
            value: "{{ .Values.app.dbName }}"
          - name: CVER_DB_USER
            value: "{{ .Values.app.dbUser }}"
          - name: CVER_DB_PASS
            valueFrom:
              secretKeyRef:
                key: mysql-password
                name: cver-mysql
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.app.debug }}
          command: ["tail", "-f", "/dev/null"]
          {{- end }}
          env:
            - name: CVER_DB_HOST
              value: "{{ .Values.app.dbHost }}"
            - name: CVER_DB_PORT
              value: "{{ .Values.app.dbPort }}"
            - name: CVER_DB_NAME
              value: "{{ .Values.app.dbName }}"
            - name: CVER_DB_USER
              value: "{{ .Values.app.dbUser }}"
            - name: CVER_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: mysql-password
                  name: cver-mysql
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
