# Quigely test values for cver-engine

replicaCount: 1

nameOverride: "stage"

app:
  apiUrl: "http://cver-api-stage"
  logLevel: "DEBUG"
  envName: "stage"
  debug: false
  cron:
    schedule:  "22 * * * *"
    suspend: false

test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-engine
  pullPolicy: Always
  tag: "stage-latest"

imagePullSecrets:
  - name: harbor
