# Quigely dev values for cver-engine

nameOverride: "dev"

app:
  apiUrl: "http://cver-api-dev"
  logLevel: "INFO"
  envName: "dev"
  debug: true
  cron:
    schedule:  "20,55 * * * *"
    suspend: true

test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-engine
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor-registry
