# Quigely dev values for cver-engine

replicaCount: 1

nameOverride: "dev"

app:
  logLevel: "INFO"
  envName: "dev"
  debug: false
  cron:
    schedule:  "5,35 * * * *"
    suspend: false
    engineDownloadLimit: 1
    engineScanLimit: 1

test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-engine
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor
