# Quigely test values for cver-engine

replicaCount: 1

nameOverride: "test"

app:
  logLevel: "DEBUG"
  envName: "test"
  debug: true
  cron:
    suspend: true

test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-engine
  pullPolicy: Always
  tag: "dev-latest"

imagePullSecrets:
  - name: harbor-registry
