# Quigely test values for cver-engine

replicaCount: 1

nameOverride: "stage"

app:
  envName: "stage"
  logLevel: "DEBUG"
  envName: "test"
  debug: false
  cron:
    schedule:  "22,52 * * * *"
    suspend: true
    engineDownloadLimit: 1
    engineScanLimit: 1

test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-engine
  pullPolicy: Always
  tag: "stage-latest"

imagePullSecrets:
  - name: harbor
