# Quigely Prod values for cver-engine

replicaCount: 1

app:
  apiUrl: "http://cver-api-stage"
  logLevel: "INFO"
  envName: "prod"
  debug: false
  cron:
    schedule:  "45 * * * *"
    suspend: false

test:
  test: true

image:
  repository: harbor.squid-ink.us/cver/cver-engine
  pullPolicy: Always
  tag: "prod-latest"

imagePullSecrets:
  - name: harbor
