apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cver-test.fullname" . }}
  labels:
    {{- include "cver-test.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cver-test.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        cver.deployed: "{{ .Values.app.deployedAt }}"
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cver-test.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: CVER_ENV
              value: "{{ .Values.app.envName }}"
            - name: CVER_LOG_LEVEL
              value: "{{ .Values.app.logLevel }}"
            - name: CVER_ENV
              value: "{{ .Values.app.envName }}"
            - name: CVER_DB_HOST
              value: "{{ .Values.app.database.host }}"
            - name: CVER_DB_PORT
              value: "{{ .Values.app.database.port }}"
            - name: CVER_DB_NAME
              value: "{{ .Values.app.database.name }}"
            - name: CVER_DB_USER
              value: "{{ .Values.app.database.user }}"
            - name: CVER_DB_PASS
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.app.database.passwordSecretName }}
                  name: {{ .Values.app.database.passwordSecretKey }}
            - name: CVER_API_URL
              value:  "{{ .Values.app.api_url }}"
            - name: CVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: admin-client-id
                  name: cver-test-creds
            - name: CVER_API_KEY
              valueFrom:
                secretKeyRef:
                  key: admin-api-key
                  name: cver-test-creds
            - name: CVER_TEST_ADMIN_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: admin-client-id
                  name: cver-test-creds
            - name: CVER_TEST_ADMIN_API_KEY
              valueFrom:
                secretKeyRef:
                  key: admin-api-key
                  name: cver-test-creds
            - name: CVER_TEST_INGEST_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: ingest-client-id
                  name: cver-test-creds
            - name: CVER_TEST_INGEST_API_KEY
              valueFrom:
                secretKeyRef:
                  key: ingest-api-key
                  name: cver-test-creds
            - name: CVER_TEST_ENGINE_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: engine-client-id
                  name: cver-test-creds
            - name: CVER_TEST_ENGINE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: engine-api-key
                  name: cver-test-creds
            - name: CVER_BRANCH
              value: "{{ .Values.app.branch }}"
            - name: CVER_TEST_DIR
              value: "{{ .Values.app.testDir }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
