apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cver-ingest.fullname" . }}
  labels:
    {{- include "cver-ingest.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.app.cron.schedule }}"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  suspend: {{ .Values.app.cron.suspend }}
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ include "cver-ingest.serviceAccountName" . }}
          imagePullSecrets:
            - name: harbor
          containers:
          - name: cver-ingest-k8s-cron
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: CVER_ENV
                value: "{{ .Values.app.envName }}"
              - name: CVER_API_URL
                value: "{{ .Values.app.apiUrl }}"
              - name: TIMEOUT_SECONDS
                value: "{{ .Values.app.timeoutSeconds }}"
              - name: CVER_DEPLOYED_AT
                value: "{{ .Values.app.deployedAt }}"
              {{- if .Values.test.test }}
              - name: CVER_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    key: ingest-client-id
                    name: cver-test-creds
              - name: CVER_API_KEY
                valueFrom:
                  secretKeyRef:
                    key: ingest-api-key
                    name: cver-test-creds
              - name: CVER_TEST
                value: "true"
              {{- else }}
              - name: CVER_CLIENT_ID
                valueFrom:
                  secretKeyRef:
                    key: client-id
                    name: cver-ingest-creds
              - name: CVER_API_KEY
                valueFrom:
                  secretKeyRef:
                    key: api-key
                    name: cver-ingest-creds
              {{- end }}
          restartPolicy: OnFailure
