{{- if eq .Values.app.envName "dev" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cver-ingest.fullname" . }}-static
  labels:
    {{- include "cver-ingest.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cver-ingest.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        cver.deployed: "{{ .Values.app.deployedAt }}"
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cver-ingest.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cver-ingest.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            privileged: true
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["tail", "-f", "/dev/null"]
          env:
            - name: CVER_ENV
              value: "{{ .Values.app.envName }}"
            - name: CVER_API_URL
              value: "{{ .Values.app.apiUrl }}"
            - name: CVER_DEPLOYED_AT
              value: "{{ .Values.app.deployedAt }}"
            - name: CVER_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: cver-ingest-creds
            - name: CVER_API_KEY
              valueFrom:
                secretKeyRef:
                  key: api-key
                  name: cver-ingest-creds
            {{- if .Values.test.test }}
            - name: CVER_TEST
              value: "true"
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
