name: Build Cver Api Container

on:
  workflow_call:
    inputs:
      tag-prefix:
        required: true
        type: string
      tag-name:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    permissions:
      pull-requests: read
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ secrets.PAT }}
          filters: |
            src:
              - 'docker/api/**'
              - 'src/**'

      - uses: docker/login-action@v2
        if: steps.changes.outputs.src == 'true'
        with:
          registry: harbor.squid-ink.us
          username: ${{ inputs.harbor-user }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Build Container
        if: steps.changes.outputs.src == 'true'
        run: |
          echo "Run Task: Build"
          export CVER_API_TAG="${{ inputs.tag-name }}"
          task build-api

      - name: Push Container
        if: steps.changes.outputs.src == 'true'
        run: |
          IMAGE_ID=$(docker images --filter "reference=politeauthority/cver-api" --format "{{.ID}}")
          docker tag ${IMAGE_ID} harbor.squid-ink.us/politeauthority/cver-api:${{ inputs.tag-name }}
          docker tag ${IMAGE_ID} harbor.squid-ink.us/politeauthority/cver-api:${{ inputs.tag-prefix }}-latest
          docker push harbor.squid-ink.us/politeauthority/cver-api:${{ inputs.tag-name }}
          docker push harbor.squid-ink.us/politeauthority/cver-api:${{ inputs.tag-prefix }}-latest
          echo "# Docker Build" >> $GITHUB_STEP_SUMMARY
          echo "**Built:** ```harbor.squid-ink.us/politeauthority/cver-api:${{ inputs.tag-name }}```" >> $GITHUB_STEP_SUMMARY
          echo "**Built:** ```harbor.squid-ink.us/politeauthority/cver-api:${{ inputs.tag-prefix }}-latest```" >> $GITHUB_STEP_SUMMARY
