name: Build Cver Test Container

on:
  workflow_call:
    inputs:
      tag-prefix:
        required: true
        type: string
      tag-name:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    permissions:
      pull-requests: read
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Add Safe Dir
        run: |
          git config --global --add safe.directory /__w/cver/cver
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ secrets.PAT }}
          filters: |
            src:
              - 'docker/test/**'
              - 'src/requirements.tx
              - 'tests/requirements.tx
      - uses: docker/login-action@v2
        with:
          registry: harbor.squid-ink.us
          username: ${{ inputs.harbor-user }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Decider
        run: |
          echo "# Docker Build: Test" >> $GITHUB_STEP_SUMMARY
          echo "ALIX DEBUG: CHANGES-OUTPUT: ${{steps.changes.outputs.src}}"
          if [ "${{steps.changes.outputs.src}}" = "false" ]; then
            echo "Skipping Test Build. No changes detected." >> $GITHUB_STEP_SUMMARY
          else
            echo "Running Test Build" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Build Container
        if: steps.changes.outputs.src == 'true'
        run: |
          echo "Run Task: Build"
          export CVER_TEST_TAG="${{ inputs.tag-name }}"
          task build-test

      - name: Push Container
        if: steps.changes.outputs.src == 'true'
        run: |
          IMAGE_ID=$(docker images --filter "reference=cver/cver-test" --format "{{.ID}}")
          docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-test:${{ inputs.tag-name }}
          docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-test:${{ inputs.tag-prefix }}-latest
          docker push harbor.squid-ink.us/cver/cver-test:${{ inputs.tag-name }}
          docker push harbor.squid-ink.us/cver/cver-test:${{ inputs.tag-prefix }}-latest
          echo "**Built:** harbor.squid-ink.us/cver/cver-test:${{ inputs.tag-name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Built:** harbor.squid-ink.us/cver/cver-test:${{ inputs.tag-prefix }}-latest" >> $GITHUB_STEP_SUMMARY
