name: Build Cver Api Container

on:
  workflow_call:
    inputs:
      tag-prefix:
        required: true
        type: string
      git-sha:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    permissions:
      pull-requests: read
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Add Safe Dir
        run: |
          git config --global --add safe.directory /__w/cver/cver
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ secrets.PAT }}
          filters: |
            src:
              - 'docker/api/**'
              - 'src/setup.py'
              - 'src/cver/api/**'
              - 'src/cver/migrate/**'
              - 'src/cver/shared/**'

      - name: Decider
        run: |
          echo "# Docker Build: Cver Api" >> $GITHUB_STEP_SUMMARY
          echo "ALIX DEBUG: CHANGES-OUTPUT: ${{steps.changes.outputs.src}}"
          if [ "${{steps.changes.outputs.src}}" = "false" ]; then
            echo "Skipping Api Build. No changes detected." >> $GITHUB_STEP_SUMMARY
          else
            echo "Running Api Build" >> $GITHUB_STEP_SUMMARY
          fi

      - uses: docker/login-action@v2
        with:
          registry: harbor.squid-ink.us
          username: ${{ inputs.harbor-user }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Extract branch name
        shell: bash
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          BRANCH="${BRANCH//\//-}"
          echo "${BRANCH}"
          echo "branch=${BRANCH}" >> "$GITHUB_OUTPUT"
        id: extract_branch

      - name: Build Container
        if: steps.changes.outputs.src == 'true'
        run: |
          echo "Run Task: Build"
          task build-api

      - name: Push Container
        if: steps.changes.outputs.src == 'true'
        run: |
          BRANCH="${{ steps.extract_branch.outputs.branch }}"
          MAKE_BRANCH_TAG="false"
          MAKE_VERSION_TAG="false"
          if [ "$BRANCH" = "stage" ]; then
            MAKE_BRANCH_TAG="false"
          elif [ "$BRANCH" = "main" ]; then
            MAKE_BRANCH_TAG="false"
            MAKE_VERSION_TAG="true"
          else
            MAKE_BRANCH_TAG="true"
          fi

          # Docker Tag
          IMAGE_ID=$(docker images --filter "reference=cver/cver-api" --format "{{.ID}}")
          docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-api:git-sha-${{ inputs.git-sha}}
          docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-prefix }}-latest

          # Docker Push
          docker push harbor.squid-ink.us/cver/cver-api:git-sha-${{ inputs.git-sha }}
          docker push harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-prefix }}-latest

          # GHA Summary
          echo "**Built:** harbor.squid-ink.us/cver/cver-api:git-sha-${{ inputs.git-sha }}" >> $GITHUB_STEP_SUMMARY
          echo "**Built:** harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-prefix }}-latest" >> $GITHUB_STEP_SUMMARY

          # Make Docker Branch Tag
          if [ "$MAKE_BRANCH_TAG" = "true" ]; then
            docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-api:git-branch-${BRANCH}
            docker push harbor.squid-ink.us/cver/cver-api:git-branch-${BRANCH}
            echo "**Built:** harbor.squid-ink.us/cver/cver-api:git-branch-${BRANCH}" >> $GITHUB_STEP_SUMMARY
          fi

          # Make Version Tag
          if [ "$MAKE_VERSION_TAG" = "true" ]; then
            VERSION=$(grep -o 'version = "[^"]*"' src/cver/api/version.py | cut -d '"' -f 2)
            docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-api:${VERSION}
            docker push harbor.squid-ink.us/cver/cver-api:${VERSION}
            echo "**Built:** harbor.squid-ink.us/cver/cver-api:${VERSION}" >> $GITHUB_STEP_SUMMARY
          fi
