name: build-python

on:
  workflow_call:


jobs:
  build-cver:
    runs-on: self-hosted
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8 pytest
          pip install -r src/requirements.txt

      - name: Build Cver Packages
        run: |
          cd src/
          python3 setup.py build
          pip install .

      - name: Source Linter
        run: |
          flake8 src/cver --config=src/flake8 --count --show-source --statistics

      - name: Test Linter
        run: |
          flake8 tests/ --config=src/flake8 --count --show-source --statistics

      - name: Run Unit Tests
        run: |
          cd src/
          pip install -r requirements.txt
          python3 setup.py build
          python3 setup.py install
          cd ../
          cd tests/
          pip install -r requirements.txt
          python3 setup.py build
          python3 setup.py install
          pytest --vcr-record=none -rx -s --md report.md unit/ 
          pytest --cov=cver --vcr-record=none -rx -s unit/ >> ./coverage.txt
          echo "ALIX-DEBUG"
          COVERAGE=$(awk '/---------- coverage: platform linux,/{flag=1} flag' "./coverage.txt")
          COVERAGE=$(awk '/TOTAL/{print $NF}' "./coverage.txt")
          cat report.md >> $GITHUB_STEP_SUMMARY
          echo "**Coverage:** ${COVERAGE}" >> $GITHUB_STEP_SUMMARY

# End File: cver/.github/workflows/build-cver.yaml
