name: build-cver

on:
  workflow_call:


jobs:
  build-cver:
    runs-on: self-hosted
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ secrets.PAT }}
          filters: |
            src:
            - 'src/**'
            - 'tests/**'

      - name: Set up Python 3.10
        if: steps.changes.outputs.src == 'true'
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        if: steps.changes.outputs.src == 'true'
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8 pytest
          pip install -r src/requirements.txt

      - name: Build Cver Packages
        if: steps.changes.outputs.src == 'true'
        run: |
          cd src/
          python3 setup.py build
          pip install .

      - name: Source Linter
        if: steps.changes.outputs.src == 'true'
        run: |
          flake8 src/cver --config=src/flake8 --count --show-source --statistics

      - name: Test Linter
        if: steps.changes.outputs.tests == 'true'
        run: |
          flake8 tests/ --config=src/flake8 --count --show-source --statistics


# End File: cver/.github/workflows/build-cver.yaml
