name: Build Cver Api Container

on:
  workflow_call:
    inputs:
      tag-prefix:
        required: true
        type: string
      tag-name:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  build:
    runs-on: self-hosted
    permissions:
      pull-requests: read
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Add Safe Dir
        run: |
          git config --global --add safe.directory /__w/cver/cver
      - uses: dorny/paths-filter@v2
        id: changes
        with:
          token: ${{ secrets.PAT }}
          filters: |
            src:
              - 'docker/api/**'
              - 'src/setup.py'
              - 'src/cver/api/**'
              - 'src/cver/migrate/**'
              - 'src/cver/shared/**'
              - 'src/cver/cver_client/**'
              - 'tests/regression/**'

      - uses: docker/login-action@v2
        with:
          registry: harbor.squid-ink.us
          username: ${{ inputs.harbor-user }}
          password: ${{ secrets.HARBOR_PASSWORD }}

      - name: Decider
        run: |
          echo "# Docker Build: Api" >> $GITHUB_STEP_SUMMARY
          echo "ALIX DEBUG: CHANGES-OUTPUT: ${{steps.changes.outputs.src}}"
          if [ "${{steps.changes.outputs.src}}" = "false" ]; then
            echo "Skipping Api Build. No changes detected." >> $GITHUB_STEP_SUMMARY
          else
            echo "Running Api Build" >> $GITHUB_STEP_SUMMARY
          fi

      - name: Extract branch name
        shell: bash
        run: |
          BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
          BRANCH="${BRANCH//\//-}"
          echo "${BRANCH }" ">> $GITHUB_OUTPUT
        id: extract_branch

      - name: Build Container
        if: steps.changes.outputs.src == 'true'
        run: |
          echo "Run Task: Build"
          export CVER_API_TAG="${{ inputs.tag-name }}"
          task build-api

      - name: Push Container
        if: steps.changes.outputs.src == 'true'
        run: |
          BRANCH="${{ steps.extract_branch.outputs.branch }}"
          MAKE_BRANCH_TAG="false"
          if [ "$BRANCH" = "stage" ]; then
            MAKE_BRANCH_TAG="false"
          elif [ "$BRANCH" = "main" ]; then
            MAKE_BRANCH_TAG="false"
          else
            MAKE_BRANCH_TAG="true"
          fi

          IMAGE_ID=$(docker images --filter "reference=cver/cver-api" --format "{{.ID}}")
          docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-name }}
          docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-prefix }}-latest
          docker push harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-name }}
          docker push harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-prefix }}-latest

          echo "**Built:** harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-name }}" >> $GITHUB_STEP_SUMMARY
          echo "**Built:** harbor.squid-ink.us/cver/cver-api:${{ inputs.tag-prefix }}-latest" >> $GITHUB_STEP_SUMMARY
          if [ "$MAKE_BRANCH_TAG" = "true" ]; then
            docker tag ${IMAGE_ID} harbor.squid-ink.us/cver/cver-api:${BRANCH}
            docker push harbor.squid-ink.us/cver/cver-api:${BRANCH}
            echo "**Built:** harbor.squid-ink.us/cver/cver-api:${BRANCH}" >> $GITHUB_STEP_SUMMARY
          fi