name: Deploy Test

on:
  workflow_call:
    inputs:
      deployment-name:
        required: true
        type: string
      git-sha:
        required: true
        type: string
      image-built:
        required: true
        type: string
      run-number:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    continue-on-error: false
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3

      - name: Extract branch name
        shell: bash
        run: |
          BRANCH="${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
          BRANCH="${BRANCH//\//-}"
          echo "${BRANCH}"
          echo "branch=${BRANCH}" >> "$GITHUB_OUTPUT"
        id: extract_branch

      - name: Deploy
        run: |
          BRANCH="${{ steps.extract_branch.outputs.branch }}"
          IMAGE_TAG="${{ inputs.deployment-name }}-latest"
          if [ "${{ inputs.deployment-name }}" = "test" ]; then
            RELEASE_NAME="cver-test-test-${{ inputs.run-number }}"
            NAMESPACE="cver-test"
            SECRET_NAME="cver-test-creds-${{ inputs.run-number }}"
            # Had to abandon this for now
            # --set "app.cverTestCredsSecret=${SECRET_NAME}" \
            DB_NAME="cver_${{ inputs.run-number }}"
            API_URL="http://cver-api-test-${{ inputs.run-number }}"
          else
            RELEASE_NAME="cver-test-${{ inputs.deployment-name}}"
            NAMESPACE="cver-${{ inputs.deployment-name}}"
            # SECRET_NAME="cver-test-creds"
            DB_NAME="cver_${{ inputs.deployment-name}}"
            API_URL="http://cver-api-${{ inputs.deployment-name }}"
          fi
          if [ "${{ inputs.image-built }}" = "true" ]; then
            IMAGE_TAG="git-sha-${{ inputs.git-sha }}"
          else
            if [ "${{ inputs.deployment-name }}" = "test" ]; then
              IMAGE_TAG="dev-latest"
              IMAGE_TAG="0.0.6"
              # this is a hack above, fix when ready
            else
              IMAGE_TAG="${{ inputs.deployment-name }}-latest"
            fi
          fi
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          chmod 600 ~/.kube/config.yaml
          DEPLOYED_AT=$(date +"%Y-%m-%d %T")
          cd helm/cver-test
          echo "Cver Api Url: ${API_URL}"
          echo "Cver-Test Image Tag: ${IMAGE_TAG}"
          echo "Cver-Test secret: ${SECRET_NAME}"
          helm upgrade \
            ${RELEASE_NAME} ./ \
            --namespace=${NAMESPACE} \
            --install \
            --wait \
            --timeout=300s \
            -f values-quigley-${{ inputs.deployment-name }}.yaml \
            --set "app.apiUrl=${API_URL}" \
            --set "app.branch=${BRANCH}" \
            --set "app.database.name=${DB_NAME}" \
            --set "app.deployedAt=${DEPLOYED_AT}" \
            --set "image.tag=${IMAGE_TAG}"
          echo "# Deployed: Cver-Test" >> $GITHUB_STEP_SUMMARY
          echo "Created Helm deployment: ${RELEASE_NAME}" >> $GITHUB_STEP_SUMMARY
          echo "Image Tag: ${IMAGE_TAG}" >> $GITHUB_STEP_SUMMARY
