name: Deploy Engine

on:
  workflow_call:
    inputs:
      deployment-name:
        required: true
        type: string
      git-sha:
        required: true
        type: string
      image-built:
        required: true
        type: string
      run-number:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    continue-on-error: false
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          if [ "${{ inputs.deployment-name }}" = "test" ]; then
            RELEASE_NAME="cver-engine-test-${{ inputs.run-number }}"
            NAMESPACE="cver-test"
            API_URL="http://cver-api-test-${{ inputs.run-number }}"
          else
            RELEASE_NAME="cver-engine-${{ inputs.deployment-name}}"
            NAMESPACE="cver-${{ inputs.deployment-name}}"
            API_URL="http://cver-api-${{ inputs.deployment-name}}"
          fi
          if [ "${{ inputs.image-built }}" = "true" ]; then
            IMAGE_TAG="git-sha-${{ inputs.git-sha }}"
          else
            if [ "${{ inputs.deployment-name }}" = "test" ]; then
              IMAGE_TAG="dev-latest"
            else
              IMAGE_TAG="${{ inputs.deployment-name }}-latest"
            fi
          fi
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          chmod 600 ~/.kube/config.yaml
          DEPLOYED_AT=$(date +"%Y-%m-%d %T")
          echo "Cver Api Url: ${API_URL}"
          cd helm/cver-engine
          helm upgrade \
            ${RELEASE_NAME} ./ \
            --namespace=${NAMESPACE} \
            --install \
            --wait \
            --timeout=300s \
            -f values-quigley-${{ inputs.deployment-name }}.yaml \
            --set "app.apiUrl=${API_URL}" \
            --set "app.dbName=${DB_NAME}" \
            --set "fullnameOverride=${RELEASE_NAME}" \
            --set "app.deployedAt=${DEPLOYED_AT}" \
            --set "image.tag=${IMAGE_TAG}"
          echo "# Deployed: Cver-Engine" >> $GITHUB_STEP_SUMMARY
          echo "Created Helm deployment: ${RELEASE_NAME}" >> $GITHUB_STEP_SUMMARY
