name: Deploy Api

on:
  workflow_call:
    inputs:
      deployment-name:
        required: true
        type: string
      run-number:
        required: true
        type: string
      tag-name:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    continue-on-error: true
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          chmod 600 ~/.kube/config.yaml
          DEPLOYED_AT=$(date +"%Y-%m-%d %T")
          kubectl get pods -n cver
          helm dependency build helm/cver-api
          helm upgrade --install \
            --namespace=cver \
            cver-api-test-${{ github.run_number }} \
            helm/cver-api/ \
            --wait \
            --timeout=120s \
            -f helm/cver-api/values-quigley-${{ inputs.deployment-name }}.yaml \
            --set "image.tag=${{ inputs.tag-name }}" \
            --set "app.dbName=cver_${{ inputs.run-number }}" \
            --set "app.deployedAt=${DEPLOYED_AT}"
          echo "# Deployed"
          echo "Created Helm deployment: cver-api-${{ inputs.deployment-name }}-${{ inputs.run-number }}" >> $GITHUB_STEP_SUMMARY
