name: Deploy Api

on:
  workflow_call:
    inputs:
      deployment-name:
        required: true
        type: string
      run-number:
        required: true
        type: string
      tag-name:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  deploy:
    runs-on: self-hosted
    continue-on-error: false
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          IMAGE_TAG="${{ inputs.deployment-name }}-latest"
          if [ "${{ inputs.deployment-name }}" = "test" ]; then
            RELEASE_NAME="cver-api-test-${{ inputs.run-number }}"
            DB_NAME="cver_${{ inputs.run-number }}"
            IMAGE_TAG="dev-latest"
          else
            RELEASE_NAME="cver-api-${{ inputs.deployment-name}}"
            DB_NAME="cver_${{ inputs.deployment-name}}"
          fi
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          chmod 600 ~/.kube/config.yaml
          DEPLOYED_AT=$(date +"%Y-%m-%d %T")
          helm dependency build helm/cver-api
          helm upgrade --install \
            --namespace=cver \
            ${RELEASE_NAME} \
            helm/cver-api/ \
            --wait \
            --timeout=120s \
            -f helm/cver-api/values-quigley-${{ inputs.deployment-name }}.yaml \
            --set "image.tag=${IMAGE_TAG}" \
            --set "app.dbName=${DB_NAME}" \
            --set "app.deployedAt=${DEPLOYED_AT}"
          if [ "${{ inputs.deployment-name }}" != "test" ]; then
            kubectl rollout restart deployment/${RELEASE_NAME}
          fi
          echo "# Deployed" >> $GITHUB_STEP_SUMMARY
          echo "Created Helm deployment: cver-api-${RELEASE_NAME}" >> $GITHUB_STEP_SUMMARY
