# # Helm Cleanup
# # Sometimes when CICD jobs fail really hard they dont cleanup properly
# #

# name: Helm Cleanup

# on:
#   schedule:
#     - cron:  '15 * * * *'

# jobs:
#   build-python:
#     runs-on: self-hosted
#     strategy:
#       fail-fast: true
#     container:
#       image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
#       credentials:
#         username: ${{ vars.HARBOR_USER }}
#         password: ${{ secrets.HARBOR_PASSWORD }}
#     steps:
#       - name: Remove Failed Helm Packages
#         run: |
#           mkdir ~/.kube
#           echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
#           export KUBECONFIG=~/.kube/config.yaml
#           chmod 600 ~/.kube/config.yaml
#           RESULT=$(helm -n cver ls | grep cver | grep failed)
#           if [ "$?" -eq 1 ]; then
#               echo "Nothing to clean up, exiting."
#               exit 0
#           fi
#           HELM_PACKAGE=$(echo "$RESULT" | awk '{print $1}')
#           helm uninstall ${HELM_PACKAGE}
#           echo "Removing ${HELM_PACKAGE}
