name: Linter

on:
  workflow_call:
    inputs:
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  helm:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    permissions:
      pull-requests: read
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Add Safe Dir
        run: |
          git config --global --add safe.directory /__w/cver/cver
      - uses: dorny/paths-filter@v2
        id: changes
        with:
            token: ${{ secrets.PAT }}
            filters: |
              helm:
                - 'helm/**'
      - name: Decider
        run: |
          echo "ALIX DEBUG: CHANGES-OUTPUT: ${{steps.changes.outputs.helm}}"
          if [ "${{steps.changes.outputs.helm}}" = "false" ]; then
            echo "Skipping Lint Helm. No changes detected." >> $GITHUB_STEP_SUMMARY
          else
            echo "Running Lint Helm. Changes detected." >> $GITHUB_STEP_SUMMARY
          fi

      - name: Veryify Helm - Cver-Api
        if: steps.changes.outputs.helm == 'true'
        run: |
          helm lint ./helm/cver-api
          cd helm/cver-api
          helm dependency build
          helm template . -f values.yaml
          helm template . -f values-quigley-dev.yaml
          helm template . -f values-quigley-stage.yaml
          helm template . -f values-quigley-test.yaml
          helm template . -f values-quigley-prod.yaml

      - name: Verify Helm - Cver-Engine
        if: steps.changes.outputs.helm == 'true'
        run: |
          helm lint ./helm/cver-engine
          cd helm/cver-engine
          helm template . -f values.yaml
          helm template . -f values-quigley-dev.yaml
          helm template . -f values-quigley-stage.yaml
          helm template . -f values-quigley-test.yaml
          helm template . -f values-quigley-prod.yaml
  
      - name: Verify Helm - Cver-Ingest
        if: steps.changes.outputs.helm == 'true'
        run: |
          helm lint ./helm/cver-ingest
          cd helm/cver-ingest
          helm template . -f values.yaml
          helm template . -f values-quigley-dev.yaml
          helm template . -f values-quigley-stage.yaml
          helm template . -f values-quigley-test.yaml
          helm template . -f values-quigley-prod.yaml

      - name: Verify Helm - Cver-Test
        if: steps.changes.outputs.helm == 'true'
        run: |
          helm lint ./helm/cver-test
          cd helm/cver-test
          helm template . -f values.yaml
          helm template . -f values-quigley-dev.yaml
          helm template . -f values-quigley-stage.yaml
          helm template . -f values-quigley-test.yaml

# End File: cver/.github/workflows/lint.yaml
