name: Linter

on:
  workflow_call:
    inputs:
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  helm:
    runs-on: self-hosted
    strategy:
      fail-fast: true
    permissions:
      pull-requests: read
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      - name: Add Safe Dir
        run: |
          git config --global --add safe.directory /__w/cver/cver
      - uses: dorny/paths-filter@v2
        id: changes
        with:
            token: ${{ secrets.PAT }}
            filters: |
              api:
                - 'helm/cver-api'
              engine:
                - 'helm/cver-engine'
              ingest:
                - 'helm/cver-ingest'
      - name: Decider
        run: |
          echo "ALIX DEBUG: CHANGES-OUTPUT: ${{steps.changes.outputs.src}}"
          if [ "${{steps.changes.outputs.src}}" = "false" ]; then
            echo "Skipping Lint Helm. No changes detected." >> $GITHUB_STEP_SUMMARY
          else
            echo "Running Lint Helm. Changes detected." >> $GITHUB_STEP_SUMMARY
          fi
      - name: Lint Helm - Cver-Api
        if: steps.changes.outputs.src == 'true'
        run: |
          helm lint ./helm/cver-api

      - name: Lint Helm - Cver-Engine
        if: steps.changes.outputs.engine == 'true'
        run: |
          helm lint ./helm/cver-engine
  
      - name: Lint Helm - Cver-Ingest
        if: steps.changes.outputs.ingest == 'true'
        run: |
          helm lint ./helm/cver-ingest
    
  