# Cver Api - Pull Request

name: Cver-Api-Pull-Request

on:
  pull_request:
    branches: "main"

jobs:
  build-python:
    runs-on: self-hosted
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8 pytest
          pip install -r src/requirements.txt

      - name: Build Packages
        run: |
          cd src/
          python3 setup.py build
          pip install .

      - name: Linter
        run: |
          cd ./src && flake8 cver --config=flake8 --count --show-source --statistics

      - name: Unit Tests
        run: pytest tests/unit

  build-docker:
    runs-on: self-hosted
    needs: build-python
    container:
      image: politeauthority/polite-cicd:0.0.1
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: |
          echo "Run Task: Build"
          export CVER_API_TAG="${{ github.sha }}"
          task build

      - uses: docker/login-action@v2
        with:
          username: politeauthority
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Container
        run: docker push politeauthority/cver-api:${{ github.sha }}

  deploy-test:
    runs-on: self-hosted
    needs: build-docker
    container:
      image: politeauthority/pignus-cicd:latest
    strategy:
      fail-fast: true
    steps:
    - uses: 'actions/checkout@v1'
    - name: 'Deploy'
      run: |
          echo $(kubectl config view)
          helm upgrade --install \
            --namespace=cver \
            cver-api-test \
            helm/cver-api/ \
            -f helm/cver-api/quigley-test-values.yaml \
            --set "image.tag=${{ github.sha }}"
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'


  # run-regression:
  #   runs-on: self-hosted
  #   needs: deploy-test
  #   container:
  #     image: politeauthority/pignus-api-dev:${{ github.sha }}
  #     env:
  #       PIGNUS_API_URL: "${{ secrets.REGRESSION_PIGNUS_API_URL }}"
  #       PIGNUS_API_CLIENT_ID: "${{ secrets.REGRESSION_PIGNUS_API_CLIENT_ID }}"
  #       PIGNUS_API_KEY: "${{ secrets.REGRESSION_PIGNUS_API_KEY }}"
  #   steps:
  #     - name: Regression Pignus-Api
  #       run: cd /tests/regression && pytest

# End File: cver/.github/webserver/pull-request.yaml
