# Cver Api - Pull Request

name: Pull Request

on:
  pull_request:
    branches: ["stage"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  
  build-cver:
    uses: ./.github/workflows/build-python.yaml
    secrets: inherit 
    permissions:
      pull-requests: read
      contents: read

  lint:
    uses: ./.github/workflows/lint.yaml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  api:
    needs: [build-cver, lint]
    uses: ./.github/workflows/build-container-api.yaml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "dev"
      tag-name: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  engine:
    needs: [build-cver, lint]
    uses: ./.github/workflows/build-container-engine.yaml
    secrets: inherit 
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "dev"
      tag-name: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-ephem-api:
    needs: [api, build-cver, lint]
    uses: ./.github/workflows/deploy-api.yaml
    secrets: inherit 
    with:
      deployment-name: "test"
      run-number: ${{ github.run_number }}
      tag-name: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-ephem-engine:
    needs: [build-cver, lint]
    uses: ./.github/workflows/deploy-engine.yaml
    secrets: inherit 
    with:
      deployment-name: "test"
      run-number: ${{ github.run_number }}
      tag-name: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  test-ephem-api:
    needs: [deploy-ephem-api, engine]
    if: ${{ needs.ephem.result == 'success' }}
    uses: ./.github/workflows/regression.yaml
    secrets: inherit 
    with:
      deployment-name: "test"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  # test-ephem-engine:
  #   needs: [ephem, engine]
  #   if: ${{ needs.ephem.result == 'success' }}
  #   uses: ./.github/workflows/regression.yaml
  #   secrets: inherit 
  #   with:
  #     deployment-name: "test"
  #     run-number: ${{ github.run_number }}
  #     cicd-version: "${{ vars.CICD_VERSION }}"
  #     harbor-user: "${{ vars.HARBOR_USER }}"

  remove-ephem:
    runs-on: self-hosted
    needs: [test-ephem-api]
    if: ${{ needs.ephem.result == 'success' }}
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ vars.CICD_VERSION }}
      credentials:
        username: ${{ vars.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Tear Down
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          echo "Remove the database"
          TEST_POD=$(kubectl get pods -n cver -l app.kubernetes.io/instance=cver-api-test-${{ github.run_number }} --no-headers | cut -d' ' -f1)
          # kubectl exec -n cver -it ${TEST_POD} -c cver-api -- /bin/cver-db-destroy
          echo "Remove the helm installation"
          helm uninstall \
            --namespace=cver \
            cver-api-test-${{ github.run_number }}
          echo "Uninstalled Helm deployment cver-api-test-${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY

# End File: cver/.github/workflows/pull-request.yaml
