# Cver Api - Pull Request

name: Cver-Api-Pull-Request

on:
  pull_request:
    branches: ["main", "staging", "jwt-auth"]

jobs:
  build-python:
    runs-on: self-hosted
    strategy:
      fail-fast: true

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install flake8 pytest
          pip install -r src/requirements.txt

      - name: Build Packages
        run: |
          cd src/
          python3 setup.py build
          pip install .

      - name: Linter
        run: |
          cd ./src && flake8 cver --config=flake8 --count --show-source --statistics

      - name: Unit Tests
        run: pytest tests/unit

  # lint-helm:
  #   runs-on: self-hosted
  #   strategy:
  #     fail-fast: true
  #   container:
  #     image: politeauthority/polite-cicd:0.0.1
  #   strategy:
  #     fail-fast: true
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Lint Helm
  #       run: |
  #         helm lint ./helm/cver-api

  build-docker:
    runs-on: self-hosted
    needs: build-python
    container:
      image: politeauthority/polite-cicd:0.0.1
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: |
          echo "Run Task: Build"
          export CVER_API_TAG="${{ github.sha }}"
          task build

      - uses: docker/login-action@v2
        with:
          username: politeauthority
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Container
        run: docker push politeauthority/cver-api:${{ github.sha }}

  deploy-test:
    runs-on: self-hosted
    needs: build-docker
    container:
      image: politeauthority/polite-cicd:0.0.1
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          kubectl get pods -n cver
          helm upgrade --install \
            --namespace=cver \
            cver-api-test-${{ github.event.number }} \
            helm/cver-api/ \
            --wait \
            -f helm/cver-api/quigley-test-values.yaml \
            --set "image.tag=${{ github.sha }}" \
            --set "app.dbName=cver_${{ github.event.number }}"

  run-test:
    runs-on: self-hosted
    needs: deploy-test
    container:
      image: politeauthority/polite-cicd:0.0.1
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          TEST_POD=$(kubectl get pods -l app.kubernetes.io/instance=cver-api-test-${{ github.event.number }} --no-headers | cut -d' ' -f1)
          kubectl exec -it ${TEST_POD} -c cver-api -- pytest /tests/regression

# End File: cver/.github/webserver/pull-request.yaml
