# Cver Api - Pull Request

name: Cver-Api-Pull-Request

on:
  pull_request:
    branches: "main"

jobs:
  build-docker:
    runs-on: self-hosted
    container:
      image: politeauthority/polite-cicd:0.0.1
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: |
          echo "Run Task: Build"
          task build

      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Container
        run: docker push politeauthority/cver-api:${{ github.sha }}

  # deploy-test:
  #   runs-on: self-hosted
  #   needs: build-docker
  #   container:
  #     image: politeauthority/pignus-cicd:latest
  #   strategy:
  #     fail-fast: true
  #   steps:
  #     - uses: actions/checkout@v1
  #     - run: |
  #         cd helm/pigus-api
  #         helm install --upgrade pignus-cicd -f values.yaml -f values-regression.yaml
  #       env:
  #         KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'

  # run-regression:
  #   runs-on: self-hosted
  #   needs: deploy-test
  #   container:
  #     image: politeauthority/pignus-api-dev:${{ github.sha }}
  #     env:
  #       PIGNUS_API_URL: "${{ secrets.REGRESSION_PIGNUS_API_URL }}"
  #       PIGNUS_API_CLIENT_ID: "${{ secrets.REGRESSION_PIGNUS_API_CLIENT_ID }}"
  #       PIGNUS_API_KEY: "${{ secrets.REGRESSION_PIGNUS_API_KEY }}"
  #   steps:
  #     - name: Regression Pignus-Api
  #       run: cd /tests/regression && pytest

# End File: cver/.github/webserver/pull-request.yaml
