# Cver Api - Push Stage

name: Push Stage

on:
  push:
    branches: ["stage"]

concurrency:
  group: "stage"
  cancel-in-progress: true

jobs:

  build-cver:
    uses: ./.github/workflows/build-cver.yaml
    secrets: inherit 
    permissions:
      pull-requests: read
      contents: read

  lint:
    uses: ./.github/workflows/lint.yaml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  build-test:
    uses: ./.github/workflows/build-container-test.yaml
    secrets: inherit 
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "stage"
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-test:
    needs: [build-test, lint]
    uses: ./.github/workflows/deploy-test.yaml
    secrets: inherit 
    with:
      deployment-name: "stage"
      git-sha: "${{ github.sha }}"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  unit-tests:
    needs: [deploy-test, build-cver]
    uses: ./.github/workflows/unit-tests.yaml
    secrets: inherit 
    with:
      deployment-name: "stage"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  build-api:
    needs: [unit-tests]
    uses: ./.github/workflows/build-container-api.yaml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "stage"
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  build-engine:
    needs: [unit-tests]
    uses: ./.github/workflows/build-container-engine.yaml
    secrets: inherit 
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "stage"
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  build-ingest:
    needs: [unit-tests]
    uses: ./.github/workflows/build-container-ingest.yaml
    secrets: inherit 
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "stage"
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-api:
    needs: [build-api]
    uses: ./.github/workflows/deploy-api.yaml
    secrets: inherit 
    with:
      deployment-name: "stage"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-ingest:
    needs: [build-ingest]
    uses: ./.github/workflows/deploy-ingest.yaml
    secrets: inherit 
    with:
      deployment-name: "stage"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-engine:
    needs: [build-engine]
    uses: ./.github/workflows/deploy-engine.yaml
    secrets: inherit
    with:
      deployment-name: "stage"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  run-ingest:
    needs: [deploy-api, deploy-ingest]
    uses: ./.github/workflows/run-ingest.yaml
    secrets: inherit 
    with:
      deployment-name: "stage"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  run-engine:
    needs: [deploy-api, deploy-engine, run-ingest]
    uses: ./.github/workflows/run-engine.yaml
    secrets: inherit 
    with:
      deployment-name: "stage"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  regression:
    needs: [deploy-api, deploy-test]
    if: ${{ needs.deploy-api.result == 'success' }}
    uses: ./.github/workflows/regression.yaml
    secrets: inherit 
    with:
      deployment-name: "stage"
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

# End File: cver/.github/workflows/push-stage.yaml
