# Cver Api - Push Stage

name: Cver-Api-Push-Stage

on:
  push:
    branches: ["staging"]

jobs:
  build-docker:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:0.0.1
      credentials:
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v3
      - name: Build Container
        run: |
          echo "Run Task: Build"
          export CVER_API_TAG="stage"
          task build
      - uses: docker/login-action@v2
        with:
          registry: ${{ secrets.HARBOR_REGISTRY }}
          username: ${{ secrets.HARBOR_USER }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Push Container
        run: |
          docker push harbor.squid-ink.us/politeauthority/cver-api:stage

  deploy-stage:
    runs-on: self-hosted
    needs: build-docker
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:0.0.1
      credentials:
        username: ${{ secrets.HARBOR_USER }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          # task cicd-decode-k8s-config -- "${{ secrets.KUBECONFIG }}" 
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          chmod 600 ~/.kube/config
          kubectl get pods -n cver
          helm upgrade --install \
            --namespace=cver \
            cver-api-stage \
            helm/cver-api/ \
            -f helm/cver-api/values-quigley-stage.yaml \

  # test-stage:
  #   runs-on: self-hosted
  #   needs: deploy-stage
  #   container:
  #     image: politeauthority/polite-cicd:0.0.1
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Deploy
  #       run: |
  #         mkdir ~/.kube
  #         echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
  #         export KUBECONFIG=~/.kube/config.yaml
  #         TEST_POD=$(kubectl get pods -l app.kubernetes.io/instance=cver-api-test-${{ github.event.number }} --no-headers | cut -d' ' -f1)
  #         (kubectl exec -it ${TEST_POD} -c cver-api -- pytest /tests/regression)



# End File: cver/.github/webserver/push-stage.yaml
