# Cver Api - Merge Main

name: Cver-Api-Push-Main

on:
  push:
    branches: ["main"]

jobs:
  build-api:
    uses: ./.github/workflows/build-container-api.yaml
    secrets: inherit
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "prod"
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  build-ingest:
    uses: ./.github/workflows/build-container-ingest.yaml
    secrets: inherit 
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "prod"
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  build-engine:
    uses: ./.github/workflows/build-container-engine.yaml
    secrets: inherit 
    permissions:
      pull-requests: read
      contents: read
    with:
      tag-prefix: "prod"
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-api:
    needs: build-api
    uses: ./.github/workflows/deploy-api.yaml
    secrets: inherit 
    with:
      deployment-name: "prod"
      run-number: ${{ github.run_number }}
      image-built: ${{ needs.build-test.outputs.image-built }}
      git-sha: "${{ github.sha }}"
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-ingest:
    needs: build-ingest
    uses: ./.github/workflows/deploy-ingest.yaml
    secrets: inherit 
    with:
      deployment-name: "stage"
      git-sha: "${{ github.sha }}"
      image-built: ${{ needs.build-test.outputs.image-built }}
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"

  deploy-engine:
    needs: build-engine
    uses: ./.github/workflows/deploy-engine.yaml
    secrets: inherit
    with:
      deployment-name: "stage"
      git-sha: "${{ github.sha }}"
      image-built: ${{ needs.build-test.outputs.image-built }}
      run-number: ${{ github.run_number }}
      cicd-version: "${{ vars.CICD_VERSION }}"
      harbor-user: "${{ vars.HARBOR_USER }}"


# End File: cver/.github/webserver/push-main.yaml
