name: Regression Ingest

on:
  workflow_call:
    inputs:
      deployment-name:
        required: true
        type: string
      run-number:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:
  regression-engine:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - uses: actions/checkout@v3
      # This needs to be updated before staging can use it.
      - name: Execute Tests
        run: |
          # @todo: Make this more dynamic
          if [ "${{ inputs.deployment-name }}" = "test" ]; then
            NAMESPACE="cver-test"
          else  
            NAMESPACE="cver-stage"
          fi
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          kubectl create job --from=cronjob/cver-ingest-test-${{ inputs.run-number }}" cver-ingest-test-${{ inputs.run-number }}-manual
          TEST_POD=$(kubectl get -n cver pods -l app.kubernetes.io/instance=cver-engine-${{ inputs.deployment-name }}-${{ inputs.run-number }} --no-headers | cut -d' ' -f1)
          kubectl exec -n cver -it ${TEST_POD} -- echo "helo world"

# End File: cver/.github/workflows/regression-ingest.yaml
