name: Regression

on:
  workflow_call:
    inputs:
      deployment-name:
        required: true
        type: string
      run-number:
        required: true
        type: string
      cicd-version:
        required: true
        type: string
      harbor-user:
        required: true
        type: string

jobs:

  api:
    runs-on: self-hosted
    container:
      image: harbor.squid-ink.us/politeauthority/polite-cicd:${{ inputs.cicd-version }}
      credentials:
        username: ${{ inputs.harbor-user }}
        password: ${{ secrets.HARBOR_PASSWORD }}
    steps:
      - name: Execute Tests
        run: |
          # @todo: Make this more dynamic
          if [ "${{ inputs.deployment-name }}" = "test" ]; then
            NAMESPACE="cver-test"
            POD_SEARCH="cver-test-${{ inputs.deployment-name }}-${{ inputs.run-number }}"
          else  
            NAMESPACE="cver-stage"
            POD_SEARCH="cver-test-stage"
          fi
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG }}" | base64 -d > ~/.kube/config.yaml
          export KUBECONFIG=~/.kube/config.yaml
          TEST_POD=$(kubectl get -n ${NAMESPACE} pods -l app.kubernetes.io/instance=${POD_SEARCH} --no-headers | cut -d' ' -f1)
          kubectl exec -n ${NAMESPACE} -it ${TEST_POD} -- cver-cicd-regression api
          REPORT=$(kubectl exec -n ${NAMESPACE} -it ${TEST_POD} -- cat /report/regression-report-api.md)
          echo "$REPORT"
          echo "${REPORT}" >> $GITHUB_STEP_SUMMARY
